### ISSUE TITLE
Create a searchable documentation.

### ISSUE THREAD

**Issue by gajena** [ROS-Aerial/aerial_robotic_landscape#21]
Creating searchable documentation can have some advantages:
* Attract more people since it will look a bit fancy.
* Reduce the friction if someone has to look through documentation frequently. 

We can still use Markdown and use something like [VuePress](https://vuepress.vuejs.org/) or [GitBook](https://www.gitbook.com/) to generate a good searchable docs.

**Comment by knmcguire** [comment]
Good point! We need to evaluate at one point in what format we want the documentation to be in at one point, appose to the assembly of markdown documents.
