### ISSUE TITLE
Add RotorPy to list of simulators

### ISSUE THREAD

**Issue by spencerfolk** [ROS-Aerial/aerial_robotic_landscape#26]
Shameless plug warning!!

We've released a Python-based UAV dynamics simulator called [RotorPy](https://github.com/spencerfolk/rotorpy) which was included in the list of simulators from the [RS4UAV workshop from ICRA 2023](https://imrclab.github.io/workshop-uav-sims-icra2023/). Particular emphasis is on lumped-parameter aerodynamic models, spatio-temporal wind fields, and applications to deep/reinforcement learning. 

As far as Python goes, the simulator is quite fast. It's been used in a few recent papers pertaining to planning or control for UAVs subject to aerodynamic wrenches, most notably as a way to quickly generate millions of quadrotor trajectories to use as training data. 

I'm always looking for ways to expand the simulator to meet the needs of researchers. I would grateful if this was added to the list of simulators here!

**Comment by knmcguire** [comment]
Ah yes absolutely. I wanted to update the simulation documentation with the content of this paper for a while but haven't had the time: https://arxiv.org/abs/2311.02296. This is the paper that resulted from that workshop.

I'm not sure when I'll have time to update this page, but if you'd like, you could be able to make a pull request for the simulation page yourself as well: https://github.com/ROS-Aerial/aerial_robotic_landscape/blob/main/simulation.md

**Comment by knmcguire** [comment]
Nevermind! Time was found and things were merged !

**Comment by aarsht7** [comment]
@spencerfolk can you help with some information on RotorPy on issue #32?

**Comment by spencerfolk** [comment]
@aarsht7 sure thanks for asking. RotorPy currently has support for Multirotor (Basic), Multirotors (Drag), and Multirotor (wind). No support for fixed-wing yet. No planned support for aerial manipulators. No support for interacting swarms yet. No planned support for cars or any other vehicles. 

Sensors include IMU, "motion capture" (noisy measurements of pose and twist). Planned support for LiDAR/depth sensor. 

Hope that helps!
