### ISSUE TITLE
Difference between RotorS/CrayS in classic Gazebo vs Ignition-Gazebo(based on RotorS) for multi-rotors? Difference in functionality ?

### ISSUE THREAD

**Issue by vbalaji21** [ROS-Aerial/aerial_robotic_landscape#33]
I have been looking to simulate Multi-rotors(mostly quadrotors) in Gazebo. I saw that RotorS framework does it in classic Gazebo and new Gazebo (Ignition-Gazebo) is based on RotorS. I am not sure of the difference in functionality among both of them and It was not clear to me.

My requirement -
1. Velocity control for multi-rotors ?
2.  Ability to give a trajectory for multi-rotors and it following it ?

**Comment by knmcguire** [comment]
Hi! 

I think that the https://robotics.stackexchange.com/ is a better place for this since not many of us checkout this issue list to handle support. Do share the link to your question posted here such that I can find someone potentially suitable to answer this question.
