### ISSUE TITLE
Get viewer statistics

### ISSUE THREAD

**Issue by knmcguire** [ROS-Aerial/aerial_robotic_landscape#46]
It would be nice to see how many people come to the website. However, it would be nice to do this completely cookieless... We are not going to use this data except for seeing how popular the website is and it would be nice to do it without the cookie notice.

I use [goatcounter](https://www.goatcounter.com/) for my personal website, which is open-source as well and doesn't track any personal data.

**Comment by TOTON95** [comment]
I haven't seen in detail how it works, but after a quick view, I like that it does not require much to get it into the site, just adding the line to the `mkdocs.yml` file.

**Comment by knmcguire** [comment]
We need to change a bit more to the project, but these are the instructions to do that: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#customization. Shouldn't be difficult?

**Comment by TOTON95** [comment]
@knmcguire we can go for that way or also add any extra js entries to mkdocs.yml, although I understand that it's for more general purposes.

**Comment by knmcguire** [comment]
Hmm that might be way easier though. It's supposed to be only one line anyway. I guess you are referring to the extra_javascript field? https://www.mkdocs.org/user-guide/configuration/#extra_javascript

**Comment by TOTON95** [comment]
@knmcguire yes! it's that one.

**Comment by knmcguire** [comment]
solved with this PR https://github.com/ROS-Aerial/aerial_robotic_landscape/pull/51
